
slowa = [
			'iluwator', 
			'kuweta', 
			'zywiol', 
			'kupa', 
			'makaron', 
			'arbuz', 
			'mysliwiec', 
			'rozrywka', 
			'krolowa', 
			'targowisko', 
			'garmazeria', 
			'mezopotamia', 
			'kratka', 
			'leszczyna', 
			'ranga', 
			'kamien', 
			'zmierzch', 
			'stukostrach', 
			'rozmaryn',
			'siermiezny', 
			'rozwiniety', 
			'sandomierski', 
			'kolaboracyjny', 
			'panienski', 
			'monotonny', 
			'gargantuiczny', 
			'kamienny', 
			'innowacyjny', 
			'nowoczesny', 
			'glupi' , 
			'halny', 
			'enigmatyczny', 
			'inwigilowany', 
			'emancypowany', 
			'podreczny', 
			'rozmarzony', 
			'trafiony', 
			'obrzydliwy'
]

rzeczowniki = [
				'iluwator', 
				'kuweta', 
				'zywiol', 
				'kupa', 
				'makaron', 
				'arbuz', 
				'mysliwiec', 
				'rozrywka', 
				'krolowa', 
				'targowisko', 
				'garmazeria', 
				'mezopotamia', 
				'kratka', 
				'leszczyna', 
				'ranga', 
				'kamien', 
				'zmierzch', 
				'stukostrach', 
				'rozmaryn'
]

przymiotniki = [
				'siermiezny', 
				'rozwiniety', 
				'sandomierski', 
				'kolaboracyjny', 
				'panienski', 
				'monotonny', 
				'gargantuiczny', 
				'kamienny', 
				'innowacyjny', 
				'nowoczesny', 
				'glupi' , 
				'halny', 
				'enigmatyczny', 
				'inwigilowany', 
				'emancypowany', 
				'podreczny', 
				'rozmarzony', 
				'trafiony', 
				'obrzydliwy'
]


